### ISSUE TITLE
Supporting saving files to s3 instead of local file system

### ISSUE THREAD

**Issue by kashalls** [VaalaCat/vorker#15]
I think this would be more beneficial for a distributed block system like minio or ceph.

**Comment by VaalaCat** [comment]
First of all, thank you for your valuable comments on Vorker

Currently Vorker uses [litefs](https://fly.io/docs/litefs/) to achieve high availability (HA).
Any files (such as code, workerd configuration files) are generated from data using the Litefs distributed database when Vorker starts, so all files can be regarded as temporary files, and Vroker does not care whether they are stored or not.

And Vorker's goal is to build a self-consistent system that does not need to rely on external components to achieve distribution and minimize various dependencies on agent conditions.

Deployers only need a docker image to fully run all the capabilities of Vorker (or even just a binary file - this will be implemented in the future)

Dependence on ceph and oss is contrary to the goals of the above vorker

If you have any other additional points please let me know

Thanks
