### ISSUE TITLE
Any plan to support “Node.js compatibility”?

### ISSUE THREAD

**Issue by CKylinMC** [VaalaCat/vorker#7]
[Node.js compatibility flag](https://developers.cloudflare.com/workers/runtime-apis/nodejs/#enable-nodejs-with-workers)

Any plan to support this feature?

**Comment by VaalaCat** [comment]
since I'm not familiar with this flag, i'm not going to add this on my roadmap for now.

But when current todos all be done, it will be implemented.

**Comment by CKylinMC** [comment]
OK, thanks!
